[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "mixed-line-ending" },
  { id = "check-yaml" },
  { id = "check-case-conflict" },
  { id = "check-json" },
  { id = "check-toml" },
  { id = "check-xml" },
  { id = "check-symlinks" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "check-executables-have-shebangs" },
  { id = "fix-byte-order-marker" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-illegal-windows-names" },
  { id = "check-shebang-scripts-are-executable" }
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-format"
name = "cargo-format"
language = "system"
pass_filenames = false
entry = "cargo fmt --check"

[[repos.hooks]]
id = "cargo-check"
name = "cargo-check"
language = "system"
pass_filenames = false
entry = "cargo check"

[[repos.hooks]]
id = "cargo-test"
name = "cargo-test"
language = "system"
pass_filenames = false
entry = "cargo test"
